#!/usr/bin/python3

import math
import sys


def is_prime(num):
    if num <= 1:
        return False
    if num <= 3:
        return True
    if num % 2 == 0 or num % 3 == 0:
        return False
    i = 5
    while i * i <= num:
        if num % i == 0 or num % (i + 2) == 0:
            return False
        i += 6
    return True


def factorize(n):
    factors = []
    while n % 2 == 0:
        factors.append(2)
        n //= 2
    i = 3
    while i * i <= n:
        while n % i == 0:
            factors.append(i)
            n //= i
        i += 2
    if n > 1:
        factors.append(n)
    return factors


def main():
    numbers = [
        4, 12, 34, 128, 1024, 4958, 1718944270642558716715,
        9, 99, 999, 9999, 9797973, 49, 239809320265259
    ]
    for number in numbers:
        factors = factorize(number)
        print(f"{number}={'*'.join(map(str, factors))}")


if __name__ == "__main__":
    main()
